# Generated by Django 4.1.7 on 2023-05-26 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(blank=True, max_length=250, null=True)),
                ('Description', models.TextField(blank=True, max_length=500, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(blank=True, choices=[('New', 'New'), ('In progress', 'In progress'), ('Ready for test', 'Ready for test'), ('Closed', 'Closed'), ('Needs info', 'Needs info'), ('Rejected', 'Rejected'), ('Posponed', 'Rejected')], default='New', max_length=50, null=True)),
                ('Type', models.CharField(blank=True, choices=[('Bug', 'Bug'), ('Question', 'Question'), ('Enhancement', 'Enhancement')], default='Bug', max_length=50, null=True)),
                ('Severity', models.CharField(blank=True, choices=[('Wishlist', 'Wishlist'), ('Minor', 'Minor'), ('Normal', 'Normal'), ('Important', 'Important'), ('Critical', 'Critical')], default='Normal', max_length=50, null=True)),
                ('Priority', models.CharField(blank=True, choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High')], default='Normal', max_length=50, null=True)),
                ('Due_Date', models.DateTimeField(blank=True, null=True)),
                ('Block_reason', models.TextField(blank=True, max_length=500, null=True)),
                ('Creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Watcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='issues.issue')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.TextField(max_length=1000)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('Issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='issues.issue')),
            ],
        ),
        migrations.CreateModel(
            name='AttachedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(blank=True, max_length=500, null=True)),
                ('File', models.FileField(blank=True, null=True, upload_to='')),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='issues.issue')),
            ],
        ),
        migrations.CreateModel(
            name='AsignedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='issues.issue')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Type', models.CharField(blank=True, choices=[('assigned to', 'assigned to'), ('due date', 'due date'), ('type', 'type'), ('severity', 'severity'), ('priority', 'priority'), ('new attachment', 'new attachment'), ('description', 'description'), ('tags added', 'tags added'), ('Blocked', 'Blocked'), ('sprint', 'sprint'), ('watches', 'watches'), ('promoted to', 'promoted to')], max_length=50, null=True)),
                ('Creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_activities', to=settings.AUTH_USER_MODEL)),
                ('Issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='issues.issue')),
                ('Old_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_assigned_user_activities', to=settings.AUTH_USER_MODEL)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='watcher',
            constraint=models.UniqueConstraint(fields=('User', 'Issue'), name='unique_migration_watcher_combination'),
        ),
        migrations.AddConstraint(
            model_name='asigneduser',
            constraint=models.UniqueConstraint(fields=('User', 'Issue'), name='unique_migration_asignedUser_combination'),
        ),
    ]
